- lib/index.js
Fixing strict error. Caused issues when used with rollup.js
> Fixing strict error

- .travis.yml
- CHANGELOG.md
- README.md
- lib/index.js
- test/all.js
- Stricter country validation and cleanup
- Only supports node version 8 or higher
> Stricter country validation and cleanup

- CHANGELOG.md
- lib/index.js
- test/all.js
Giving Austria some somewhat more specific validation rules and correcting a typo in the tests. Info on the specific rules for Austria that I found online is partially contradictory, however, one thing that there's consensus on is that the PLZs do not start with 0, in addition to being 4-digits long, as already specified previously.
I also fixed an unrelated typo of sorts in the tests.
@melwynfurtado possibly?
> More specific Regex for Austrian postal codes and tests for that

- README.md
- lib/index.js
- package-lock.json
- package.json
- test/all.js
- Add support for Ireland postcodes (Issue: #15)
N/A
> Add support for Ireland postcodes

- .gitignore
- CHANGELOG.md
> Update changelog v2.1.0

- .gitignore
- CHANGELOG.md
- README.md
- lib/index.js
- package-lock.json
- package.json
- test/all.js
- Release v2.1.0 to Master
N/A
> Release v2.1.0 to Master

- CHANGELOG.md
- README.md
- src/main.ts
- test/main.spec.ts
This adds a method to check if a validation exists for a country.
This will enable us to determine whether a specific country code supports validation or not before attempting it.
@melwynfurtado
> Added function to check if a country supports validation

- README.md
> to postcodeValidatorExistsForCountry updated

- CHANGELOG.md
- src/postcode-regexes.ts
Update validation of Korean zip codes. They changed their zip codes in 2015. https://postal-codes.cybo.com/south-korea/
> Fix Korea (KR)

- CHANGELOG.md
- package-lock.json
- package.json
- src/main.ts
- Export country codes as types for typescript
- Update dev dependencies to overcome security vulnerabilities
- Update change log for `v3.2.0`
> Update changelog for v3.2.0 and export country code type

- .gitignore
- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/main.ts
- src/postcode-regexes.ts
- src/postcode-types.ts
- test/main.spec.ts
> Merge/release v3.2.0 into master

- package-lock.json
- package.json
- src/main.ts
- src/postcode-regexes.ts
> Master into develop

- .github/workflows/npm-publish.yml
- package.json
> Remove older release npm scripts

- .github/workflows/npm-publish.yml
> fix: update github workflow name

- .github/workflows/npm-test.yml
- .travis.yml
> Migrate from Travis CI to Github Actions

- CONTRIBUTING.md
> fix: test doc

- package-lock.json
> fix: package-lock.json version

- src/postcode-regexes.ts
- src/postcode-types.ts
Update Vietnam postcode
Anyone
> feat: update Vietnam postcode

- package-lock.json
- package.json
- release.config.js
- scripts/prepare.js
> ci: update deps and add release notes

- package-lock.json
- src/postcode-regexes.ts
- src/postcode-types.ts
- test/main.spec.ts
re #83
Include Cayman Islands postal code validation
@melwynfurtado
> feat(postcode-regexes.ts): Include Cayman Islands

- .github/workflows/release.yml
- .github/workflows/test.yml
- package-lock.json
upgrade node.js to 18
@melwynfurtado
> ci: upgrade node.js to 18

- src/postcode-regexes.ts
- src/postcode-types.ts
- test/main.spec.ts
Peru was missing from supported countries
anyone
> Added Peru PE

- .github/workflows/release.yml
- .github/workflows/test.yml
update github actions to latest versions
@melwynfurtado 😄
> chore: update github actions to latest versions

- release.config.js
> chore: fixup release version tag
